sudo: required
language: nodejs

services:
  - docker
  - mongodb

install:
  - git clone --branch alyssa_branch git@github.com:URAP-charter/web_scraping.git flaskserver

script:
  - cd testing && ./test.sh