version: "2"

services:
    client:
        build: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        networks:
            - scraping_server_network

    server:
        build: ./server
        restart: always
        ports:
           - "8000:8000"
        volumes:
           - ./server:/server
           - /server/node_modules
        depends_on:
           - mongodb
        networks:
            - scraping_server_network

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
           - ./data-node:/data/db
        ports:
           - 27017:27017
        command: mongod --noauth
        networks:
           - scraping_server_network

networks:
    scraping_server_network:
        driver: bridge